version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  Install-Deps:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - node/install-packages
  node/test:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - test-results-for: jest

workflows:
  Test:
    jobs:
      - Install-Deps
      - node/test:
          requires:
            - Install-Deps