version: 2.1
jobs:
  unit:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            npm install
            npm test

          